emit:
  #- "@typespec/openapi3"
  - "@azure-tools/typespec-python"
  - "@azure-tools/typespec-java"
  #- "@azure-tools/typespec-ts"
options:
  "@azure-tools/typespec-python":
    package-pprint-name: "Brian Fun Service"
    package-dir: "brian-fun-service"
    package-name: "{package-dir}"
    unbranded: true
  "@azure-tools/typespec-java":
    package-dir: "brian-fun-service"
    namespace: "com.brian.fun.service"
    branded: false
  "@azure-tools/typespec-ts":
    title: "Brian Fun Service"
    package-dir: "brian-fun-service"
    generateMetadata: true
    unbranded: true
    packageDetails:
      name: "@azure-rest/brian-fun-service"
      description: "Brian Fun Service"
      version: "1.0.0-beta.1"
