// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.brian.fun.service;

public final class ReadmeSamples {
    public void readmeSamples() {
        // BEGIN: com.brian.fun.service.readme
        // END: com.brian.fun.service.readme
    }
}
