// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.brian.fun.service.models;

import com.generic.core.annotation.Fluent;
import com.generic.core.annotation.Generated;
import com.generic.core.models.BinaryData;

/**
 * The file details model for the contents.
 */
@Fluent
public final class ContentsFileDetails {
    /*
     * The content of the file
     */
    @Generated
    private BinaryData content;

    /*
     * The filename of the file
     */
    @Generated
    private String filename;

    /*
     * The content-type of the file
     */
    @Generated
    private String contentType = "application/octet-stream";

    /**
     * Creates an instance of ContentsFileDetails class.
     * 
     * @param content the content value to set.
     */
    @Generated
    public ContentsFileDetails(BinaryData content) {
        this.content = content;
    }

    /**
     * Get the content property: The content of the file.
     * 
     * @return the content value.
     */
    @Generated
    public BinaryData getContent() {
        return this.content;
    }

    /**
     * Get the filename property: The filename of the file.
     * 
     * @return the filename value.
     */
    @Generated
    public String getFilename() {
        return this.filename;
    }

    /**
     * Set the filename property: The filename of the file.
     * 
     * @param filename the filename value to set.
     * @return the ContentsFileDetails object itself.
     */
    @Generated
    public ContentsFileDetails setFilename(String filename) {
        this.filename = filename;
        return this;
    }

    /**
     * Get the contentType property: The content-type of the file.
     * 
     * @return the contentType value.
     */
    @Generated
    public String getContentType() {
        return this.contentType;
    }

    /**
     * Set the contentType property: The content-type of the file.
     * 
     * @param contentType the contentType value to set.
     * @return the ContentsFileDetails object itself.
     */
    @Generated
    public ContentsFileDetails setContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
}
