// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.brian.fun.service.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.generic.core.annotation.Generated;
import com.generic.core.annotation.Immutable;

/**
 * The TodoFileAttachment model.
 */
@Immutable
public final class TodoFileAttachment {
    /*
     * The todo item this is attached to
     */
    @Generated
    @JsonProperty(value = "todoItemId", access = JsonProperty.Access.WRITE_ONLY)
    private long todoItemId;

    /*
     * The file name of the attachment
     */
    @Generated
    @JsonProperty(value = "filename")
    private String filename;

    /*
     * The media type of the attachment
     */
    @Generated
    @JsonProperty(value = "mediaType")
    private String mediaType;

    /*
     * The url where the attachment can be downloaded from
     */
    @Generated
    @JsonProperty(value = "url", access = JsonProperty.Access.WRITE_ONLY)
    private String url;

    /*
     * The contents of the file
     */
    @Generated
    @JsonProperty(value = "contents")
    private byte[] contents;

    /**
     * Creates an instance of TodoFileAttachment class.
     * 
     * @param filename the filename value to set.
     * @param mediaType the mediaType value to set.
     * @param contents the contents value to set.
     */
    @Generated
    @JsonCreator
    public TodoFileAttachment(@JsonProperty(value = "filename") String filename,
        @JsonProperty(value = "mediaType") String mediaType, @JsonProperty(value = "contents") byte[] contents) {
        this.filename = filename;
        this.mediaType = mediaType;
        this.contents = contents;
    }

    /**
     * Get the todoItemId property: The todo item this is attached to.
     * 
     * @return the todoItemId value.
     */
    @Generated
    public long getTodoItemId() {
        return this.todoItemId;
    }

    /**
     * Get the filename property: The file name of the attachment.
     * 
     * @return the filename value.
     */
    @Generated
    public String getFilename() {
        return this.filename;
    }

    /**
     * Get the mediaType property: The media type of the attachment.
     * 
     * @return the mediaType value.
     */
    @Generated
    public String getMediaType() {
        return this.mediaType;
    }

    /**
     * Get the url property: The url where the attachment can be downloaded from.
     * 
     * @return the url value.
     */
    @Generated
    public String getUrl() {
        return this.url;
    }

    /**
     * Get the contents property: The contents of the file.
     * 
     * @return the contents value.
     */
    @Generated
    public byte[] getContents() {
        return this.contents;
    }
}
