// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.brian.fun.service.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.generic.core.annotation.Fluent;
import com.generic.core.annotation.Generated;

/**
 * The TodoLabelRecord model.
 */
@Fluent
public final class TodoLabelRecord {
    /*
     * The name property.
     */
    @Generated
    @JsonProperty(value = "name")
    private String name;

    /*
     * The color property.
     */
    @Generated
    @JsonProperty(value = "color")
    private String color;

    /**
     * Creates an instance of TodoLabelRecord class.
     * 
     * @param name the name value to set.
     */
    @Generated
    @JsonCreator
    public TodoLabelRecord(@JsonProperty(value = "name") String name) {
        this.name = name;
    }

    /**
     * Get the name property: The name property.
     * 
     * @return the name value.
     */
    @Generated
    public String getName() {
        return this.name;
    }

    /**
     * Get the color property: The color property.
     * 
     * @return the color value.
     */
    @Generated
    public String getColor() {
        return this.color;
    }

    /**
     * Set the color property: The color property.
     * 
     * @param color the color value to set.
     * @return the TodoLabelRecord object itself.
     */
    @Generated
    public TodoLabelRecord setColor(String color) {
        this.color = color;
        return this;
    }
}
