// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.brian.fun.service.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.generic.core.annotation.Generated;
import com.generic.core.annotation.Immutable;
import java.util.List;

/**
 * The TodoPage model.
 */
@Immutable
public final class TodoPage {
    /*
     * The items in the page
     */
    @Generated
    @JsonProperty(value = "items")
    private List<TodoItem> items;

    /*
     * The pagination property.
     */
    @Generated
    @JsonProperty(value = "pagination")
    private TodoPagePagination pagination;

    /**
     * Creates an instance of TodoPage class.
     * 
     * @param items the items value to set.
     * @param pagination the pagination value to set.
     */
    @Generated
    @JsonCreator
    private TodoPage(@JsonProperty(value = "items") List<TodoItem> items,
        @JsonProperty(value = "pagination") TodoPagePagination pagination) {
        this.items = items;
        this.pagination = pagination;
    }

    /**
     * Get the items property: The items in the page.
     * 
     * @return the items value.
     */
    @Generated
    public List<TodoItem> getItems() {
        return this.items;
    }

    /**
     * Get the pagination property: The pagination property.
     * 
     * @return the pagination value.
     */
    @Generated
    public TodoPagePagination getPagination() {
        return this.pagination;
    }
}
