// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.brian.fun.service.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.generic.core.annotation.Generated;
import com.generic.core.annotation.Immutable;

/**
 * The TodoUrlAttachment model.
 */
@Immutable
public final class TodoUrlAttachment {
    /*
     * A description of the URL
     */
    @Generated
    @JsonProperty(value = "description")
    private String description;

    /*
     * The url
     */
    @Generated
    @JsonProperty(value = "url")
    private String url;

    /**
     * Creates an instance of TodoUrlAttachment class.
     * 
     * @param description the description value to set.
     * @param url the url value to set.
     */
    @Generated
    @JsonCreator
    public TodoUrlAttachment(@JsonProperty(value = "description") String description,
        @JsonProperty(value = "url") String url) {
        this.description = description;
        this.url = url;
    }

    /**
     * Get the description property: A description of the URL.
     * 
     * @return the description value.
     */
    @Generated
    public String getDescription() {
        return this.description;
    }

    /**
     * Get the url property: The url.
     * 
     * @return the url value.
     */
    @Generated
    public String getUrl() {
        return this.url;
    }
}
