// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.brian.fun.service.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.generic.core.annotation.Fluent;
import com.generic.core.annotation.Generated;
import com.generic.core.models.BinaryData;
import java.time.OffsetDateTime;
import java.util.List;

/**
 * The TodoItem model.
 */
@Fluent
public final class TodoItem {
    /*
     * The item's unique id
     */
    @Generated
    @JsonProperty(value = "id")
    private long id;

    /*
     * The item's title
     */
    @Generated
    @JsonProperty(value = "title")
    private String title;

    /*
     * User that created the todo
     */
    @Generated
    @JsonProperty(value = "createdBy", access = JsonProperty.Access.WRITE_ONLY)
    private long createdBy;

    /*
     * User that the todo is assigned to
     */
    @Generated
    @JsonProperty(value = "assignedTo")
    private Long assignedTo;

    /*
     * A longer description of the todo item in markdown format
     */
    @Generated
    @JsonProperty(value = "description")
    private String description;

    /*
     * The status of the todo item
     */
    @Generated
    @JsonProperty(value = "status")
    private TodoItemStatus status;

    /*
     * When the todo item was created.
     */
    @Generated
    @JsonProperty(value = "createdAt", access = JsonProperty.Access.WRITE_ONLY)
    private OffsetDateTime createdAt;

    /*
     * When the todo item was last updated
     */
    @Generated
    @JsonProperty(value = "updatedAt", access = JsonProperty.Access.WRITE_ONLY)
    private OffsetDateTime updatedAt;

    /*
     * When the todo item was makred as completed
     */
    @Generated
    @JsonProperty(value = "completedAt", access = JsonProperty.Access.WRITE_ONLY)
    private OffsetDateTime completedAt;

    /*
     * The labels property.
     */
    @Generated
    @JsonProperty(value = "labels")
    private List<BinaryData> labels;

    /**
     * Creates an instance of TodoItem class.
     * 
     * @param id the id value to set.
     * @param title the title value to set.
     * @param status the status value to set.
     * @param labels the labels value to set.
     */
    @Generated
    @JsonCreator
    public TodoItem(@JsonProperty(value = "id") long id, @JsonProperty(value = "title") String title,
        @JsonProperty(value = "status") TodoItemStatus status,
        @JsonProperty(value = "labels") List<BinaryData> labels) {
        this.id = id;
        this.title = title;
        this.status = status;
        this.labels = labels;
    }

    /**
     * Get the id property: The item's unique id.
     * 
     * @return the id value.
     */
    @Generated
    public long getId() {
        return this.id;
    }

    /**
     * Get the title property: The item's title.
     * 
     * @return the title value.
     */
    @Generated
    public String getTitle() {
        return this.title;
    }

    /**
     * Get the createdBy property: User that created the todo.
     * 
     * @return the createdBy value.
     */
    @Generated
    public long getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Get the assignedTo property: User that the todo is assigned to.
     * 
     * @return the assignedTo value.
     */
    @Generated
    public Long getAssignedTo() {
        return this.assignedTo;
    }

    /**
     * Set the assignedTo property: User that the todo is assigned to.
     * 
     * @param assignedTo the assignedTo value to set.
     * @return the TodoItem object itself.
     */
    @Generated
    public TodoItem setAssignedTo(Long assignedTo) {
        this.assignedTo = assignedTo;
        return this;
    }

    /**
     * Get the description property: A longer description of the todo item in markdown format.
     * 
     * @return the description value.
     */
    @Generated
    public String getDescription() {
        return this.description;
    }

    /**
     * Set the description property: A longer description of the todo item in markdown format.
     * 
     * @param description the description value to set.
     * @return the TodoItem object itself.
     */
    @Generated
    public TodoItem setDescription(String description) {
        this.description = description;
        return this;
    }

    /**
     * Get the status property: The status of the todo item.
     * 
     * @return the status value.
     */
    @Generated
    public TodoItemStatus getStatus() {
        return this.status;
    }

    /**
     * Get the createdAt property: When the todo item was created.
     * 
     * @return the createdAt value.
     */
    @Generated
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Get the updatedAt property: When the todo item was last updated.
     * 
     * @return the updatedAt value.
     */
    @Generated
    public OffsetDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Get the completedAt property: When the todo item was makred as completed.
     * 
     * @return the completedAt value.
     */
    @Generated
    public OffsetDateTime getCompletedAt() {
        return this.completedAt;
    }

    /**
     * Get the labels property: The labels property.
     * 
     * @return the labels value.
     */
    @Generated
    public List<BinaryData> getLabels() {
        return this.labels;
    }
}
