// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.brian.fun.service;

import com.azure.core.util.serializer.TypeReference;
import com.brian.fun.service.implementation.MultipartFormDataHelper;
import com.brian.fun.service.implementation.TodoItemsAttachmentsImpl;
import com.brian.fun.service.implementation.models.CreateFileAttachmentRequest;
import com.brian.fun.service.implementation.models.CreateUrlAttachmentRequest;
import com.brian.fun.service.models.ContentsFileDetails;
import com.brian.fun.service.models.TodoUrlAttachment;
import com.generic.core.annotation.Generated;
import com.generic.core.annotation.ReturnType;
import com.generic.core.annotation.ServiceClient;
import com.generic.core.annotation.ServiceMethod;
import com.generic.core.exception.ClientAuthenticationException;
import com.generic.core.exception.HttpResponseException;
import com.generic.core.exception.ResourceModifiedException;
import com.generic.core.http.Response;
import com.generic.core.models.BinaryData;
import com.generic.core.models.RequestOptions;
import java.util.List;

/**
 * Initializes a new instance of the synchronous TodoClient type.
 */
@ServiceClient(builder = TodoClientBuilder.class)
public final class TodoItemsAttachmentsClient {
    @Generated
    private final TodoItemsAttachmentsImpl serviceClient;

    /**
     * Initializes an instance of TodoItemsAttachmentsClient class.
     * 
     * @param serviceClient the service client implementation.
     */
    @Generated
    TodoItemsAttachmentsClient(TodoItemsAttachmentsImpl serviceClient) {
        this.serviceClient = serviceClient;
    }

    /**
     * The list operation.
     * <p>
     * <strong>Response Body Schema</strong>
     * </p>
     * <pre>{@code
     * [
     *     BinaryData (Required)
     * ]
     * }</pre>
     * 
     * @param itemId An integer that can be serialized to JSON (`−9007199254740991 (−(2^53 − 1))` to `9007199254740991
     * (2^53 − 1)` ).
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @return the response.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<BinaryData> listWithResponse(long itemId, RequestOptions requestOptions) {
        return this.serviceClient.listWithResponse(itemId, requestOptions);
    }

    /**
     * The createUrlAttachment operation.
     * <p>
     * <strong>Request Body Schema</strong>
     * </p>
     * <pre>{@code
     * {
     *     contents (Required): {
     *         description: String (Required)
     *         url: String (Required)
     *     }
     * }
     * }</pre>
     * 
     * @param itemId An integer that can be serialized to JSON (`−9007199254740991 (−(2^53 − 1))` to `9007199254740991
     * (2^53 − 1)` ).
     * @param request The request parameter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @return the response.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<Void> createUrlAttachmentWithResponse(long itemId, BinaryData request,
        RequestOptions requestOptions) {
        return this.serviceClient.createUrlAttachmentWithResponse(itemId, request, requestOptions);
    }

    /**
     * The createFileAttachment operation.
     * 
     * @param itemId An integer that can be serialized to JSON (`−9007199254740991 (−(2^53 − 1))` to `9007199254740991
     * (2^53 − 1)` ).
     * @param request The request parameter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @return the response.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    Response<Void> createFileAttachmentWithResponse(long itemId, BinaryData request, RequestOptions requestOptions) {
        // Protocol API requires serialization of parts with content-disposition and data, as operation
        // 'createFileAttachment' is 'multipart/form-data'
        return this.serviceClient.createFileAttachmentWithResponse(itemId, request, requestOptions);
    }

    /**
     * The list operation.
     * 
     * @param itemId An integer that can be serialized to JSON (`−9007199254740991 (−(2^53 − 1))` to `9007199254740991
     * (2^53 − 1)` ).
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public List<BinaryData> list(long itemId) {
        // Generated convenience method for listWithResponse
        RequestOptions requestOptions = new RequestOptions();
        return listWithResponse(itemId, requestOptions).getValue().toObject(TYPE_REFERENCE_LIST_BINARY_DATA);
    }

    /**
     * The createUrlAttachment operation.
     * 
     * @param itemId An integer that can be serialized to JSON (`−9007199254740991 (−(2^53 − 1))` to `9007199254740991
     * (2^53 − 1)` ).
     * @param contents The contents parameter.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public void createUrlAttachment(long itemId, TodoUrlAttachment contents) {
        // Generated convenience method for createUrlAttachmentWithResponse
        RequestOptions requestOptions = new RequestOptions();
        CreateUrlAttachmentRequest requestObj = new CreateUrlAttachmentRequest(contents);
        BinaryData request = BinaryData.fromObject(requestObj);
        createUrlAttachmentWithResponse(itemId, request, requestOptions).getValue();
    }

    /**
     * The createFileAttachment operation.
     * 
     * @param itemId An integer that can be serialized to JSON (`−9007199254740991 (−(2^53 − 1))` to `9007199254740991
     * (2^53 − 1)` ).
     * @param contents Represent a byte array.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public void createFileAttachment(long itemId, ContentsFileDetails contents) {
        // Generated convenience method for createFileAttachmentWithResponse
        RequestOptions requestOptions = new RequestOptions();
        CreateFileAttachmentRequest requestObj = new CreateFileAttachmentRequest(contents);
        BinaryData request = new MultipartFormDataHelper(requestOptions)
            .serializeFileField("contents", requestObj.getContents().getContent(),
                requestObj.getContents().getContentType(), requestObj.getContents().getFilename())
            .end().getRequestBody();
        createFileAttachmentWithResponse(itemId, request, requestOptions).getValue();
    }

    @Generated
    private static final TypeReference<List<BinaryData>> TYPE_REFERENCE_LIST_BINARY_DATA
        = new TypeReference<List<BinaryData>>() {
        };
}
