// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.brian.fun.service;

import com.brian.fun.service.implementation.UsersImpl;
import com.brian.fun.service.implementation.models.CreateRequest;
import com.brian.fun.service.implementation.models.ForgotPasswordRequest;
import com.brian.fun.service.implementation.models.LoginRequest;
import com.brian.fun.service.models.User;
import com.brian.fun.service.models.UserCreatedResponse;
import com.generic.core.annotation.Generated;
import com.generic.core.annotation.ReturnType;
import com.generic.core.annotation.ServiceClient;
import com.generic.core.annotation.ServiceMethod;
import com.generic.core.exception.ClientAuthenticationException;
import com.generic.core.exception.HttpResponseException;
import com.generic.core.exception.ResourceModifiedException;
import com.generic.core.exception.ResourceNotFoundException;
import com.generic.core.http.Response;
import com.generic.core.models.BinaryData;
import com.generic.core.models.RequestOptions;

/**
 * Initializes a new instance of the synchronous TodoClient type.
 */
@ServiceClient(builder = TodoClientBuilder.class)
public final class UsersClient {
    @Generated
    private final UsersImpl serviceClient;

    /**
     * Initializes an instance of UsersClient class.
     * 
     * @param serviceClient the service client implementation.
     */
    @Generated
    UsersClient(UsersImpl serviceClient) {
        this.serviceClient = serviceClient;
    }

    /**
     * The create operation.
     * <p>
     * <strong>Request Body Schema</strong>
     * </p>
     * <pre>{@code
     * {
     *     user (Required): {
     *         id: long (Required)
     *         username: String (Required)
     *         email: String (Required)
     *         password: String (Required)
     *     }
     * }
     * }</pre>
     * <p>
     * <strong>Response Body Schema</strong>
     * </p>
     * <pre>{@code
     * {
     *     id: long (Required)
     *     username: String (Required)
     *     email: String (Required)
     *     password: String (Required)
     *     token: String (Required)
     * }
     * }</pre>
     * 
     * @param request The request parameter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @return the response.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<BinaryData> createWithResponse(BinaryData request, RequestOptions requestOptions) {
        return this.serviceClient.createWithResponse(request, requestOptions);
    }

    /**
     * The validate operation.
     * 
     * @param token A sequence of textual characters.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @return the response.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<Void> validateWithResponse(String token, RequestOptions requestOptions) {
        return this.serviceClient.validateWithResponse(token, requestOptions);
    }

    /**
     * The login operation.
     * <p>
     * <strong>Request Body Schema</strong>
     * </p>
     * <pre>{@code
     * {
     *     username: String (Required)
     *     password: String (Required)
     * }
     * }</pre>
     * 
     * @param request The request parameter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @return the response.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<Void> loginWithResponse(BinaryData request, RequestOptions requestOptions) {
        return this.serviceClient.loginWithResponse(request, requestOptions);
    }

    /**
     * The logout operation.
     * 
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @return the response.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<Void> logoutWithResponse(RequestOptions requestOptions) {
        return this.serviceClient.logoutWithResponse(requestOptions);
    }

    /**
     * Sends a reset token to the user's email address.
     * <p>
     * <strong>Request Body Schema</strong>
     * </p>
     * <pre>{@code
     * {
     *     email: String (Required)
     * }
     * }</pre>
     * 
     * @param request The request parameter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @return the response.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<Void> forgotPasswordWithResponse(BinaryData request, RequestOptions requestOptions) {
        return this.serviceClient.forgotPasswordWithResponse(request, requestOptions);
    }

    /**
     * The resetPassword operation.
     * 
     * @param resetToken A sequence of textual characters.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @return the response.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<Void> resetPasswordWithResponse(String resetToken, RequestOptions requestOptions) {
        return this.serviceClient.resetPasswordWithResponse(resetToken, requestOptions);
    }

    /**
     * The create operation.
     * 
     * @param user The user parameter.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public UserCreatedResponse create(User user) {
        // Generated convenience method for createWithResponse
        RequestOptions requestOptions = new RequestOptions();
        CreateRequest requestObj = new CreateRequest(user);
        BinaryData request = BinaryData.fromObject(requestObj);
        return createWithResponse(request, requestOptions).getValue().toObject(UserCreatedResponse.class);
    }

    /**
     * The validate operation.
     * 
     * @param token A sequence of textual characters.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public void validate(String token) {
        // Generated convenience method for validateWithResponse
        RequestOptions requestOptions = new RequestOptions();
        validateWithResponse(token, requestOptions).getValue();
    }

    /**
     * The login operation.
     * 
     * @param username A sequence of textual characters.
     * @param password A sequence of textual characters.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public void login(String username, String password) {
        // Generated convenience method for loginWithResponse
        RequestOptions requestOptions = new RequestOptions();
        LoginRequest requestObj = new LoginRequest(username, password);
        BinaryData request = BinaryData.fromObject(requestObj);
        loginWithResponse(request, requestOptions).getValue();
    }

    /**
     * The logout operation.
     * 
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public void logout() {
        // Generated convenience method for logoutWithResponse
        RequestOptions requestOptions = new RequestOptions();
        logoutWithResponse(requestOptions).getValue();
    }

    /**
     * Sends a reset token to the user's email address.
     * 
     * @param email A sequence of textual characters.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public void forgotPassword(String email) {
        // Generated convenience method for forgotPasswordWithResponse
        RequestOptions requestOptions = new RequestOptions();
        ForgotPasswordRequest requestObj = new ForgotPasswordRequest(email);
        BinaryData request = BinaryData.fromObject(requestObj);
        forgotPasswordWithResponse(request, requestOptions).getValue();
    }

    /**
     * The resetPassword operation.
     * 
     * @param resetToken A sequence of textual characters.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public void resetPassword(String resetToken) {
        // Generated convenience method for resetPasswordWithResponse
        RequestOptions requestOptions = new RequestOptions();
        resetPasswordWithResponse(resetToken, requestOptions).getValue();
    }
}
