// Code generated by Microsoft (R) TypeSpec Code Generator.

module com.brian.fun.service {
    requires transitive com.generic.core;
    exports com.brian.fun.service;
    exports com.brian.fun.service.models;
    opens com.brian.fun.service.models to com.generic.core, com.fasterxml.jackson.databind;
    opens com.brian.fun.service.implementation.models to com.generic.core, com.fasterxml.jackson.databind;
}
