// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.brian.fun.service.implementation;

import com.brian.fun.service.implementation.models.UpdateRequest;

/**
 * This is the Helper class to enable json merge patch serialization for a model.
 */
public class JsonMergePatchHelper {
    private static UpdateRequestAccessor updateRequestAccessor;

    public interface UpdateRequestAccessor {
        UpdateRequest prepareModelForJsonMergePatch(UpdateRequest updateRequest, boolean jsonMergePatchEnabled);
    }

    public static void setUpdateRequestAccessor(UpdateRequestAccessor accessor) {
        updateRequestAccessor = accessor;
    }

    public static UpdateRequestAccessor getUpdateRequestAccessor() {
        return updateRequestAccessor;
    }
}
