// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.brian.fun.service.implementation.models;

import com.brian.fun.service.models.User;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.generic.core.annotation.Generated;
import com.generic.core.annotation.Immutable;

/**
 * The CreateRequest model.
 */
@Immutable
public final class CreateRequest {
    /*
     * The user property.
     */
    @Generated
    @JsonProperty(value = "user")
    private User user;

    /**
     * Creates an instance of CreateRequest class.
     * 
     * @param user the user value to set.
     */
    @Generated
    @JsonCreator
    public CreateRequest(@JsonProperty(value = "user") User user) {
        this.user = user;
    }

    /**
     * Get the user property: The user property.
     * 
     * @return the user value.
     */
    @Generated
    public User getUser() {
        return this.user;
    }
}
