// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.brian.fun.service.implementation.models;

import com.brian.fun.service.models.TodoItem;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.generic.core.annotation.Generated;
import com.generic.core.annotation.Immutable;
import com.generic.core.models.BinaryData;
import java.util.List;

/**
 * The CreateJsonRequest model.
 */
@Immutable
public final class CreateJsonRequest {
    /*
     * The item property.
     */
    @Generated
    @JsonProperty(value = "item")
    private TodoItem item;

    /*
     * The attachments property.
     */
    @Generated
    @JsonProperty(value = "attachments")
    private List<BinaryData> attachments;

    /**
     * Creates an instance of CreateJsonRequest class.
     * 
     * @param item the item value to set.
     * @param attachments the attachments value to set.
     */
    @Generated
    @JsonCreator
    public CreateJsonRequest(@JsonProperty(value = "item") TodoItem item,
        @JsonProperty(value = "attachments") List<BinaryData> attachments) {
        this.item = item;
        this.attachments = attachments;
    }

    /**
     * Get the item property: The item property.
     * 
     * @return the item value.
     */
    @Generated
    public TodoItem getItem() {
        return this.item;
    }

    /**
     * Get the attachments property: The attachments property.
     * 
     * @return the attachments value.
     */
    @Generated
    public List<BinaryData> getAttachments() {
        return this.attachments;
    }
}
