// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.brian.fun.service.implementation.models;

import com.brian.fun.service.models.ContentsFileDetails;
import com.generic.core.annotation.Generated;
import com.generic.core.annotation.Immutable;

/**
 * The CreateFileAttachmentRequest model.
 */
@Immutable
public final class CreateFileAttachmentRequest {
    /*
     * The contents property.
     */
    @Generated
    private ContentsFileDetails contents;

    /**
     * Creates an instance of CreateFileAttachmentRequest class.
     * 
     * @param contents the contents value to set.
     */
    @Generated
    public CreateFileAttachmentRequest(ContentsFileDetails contents) {
        this.contents = contents;
    }

    /**
     * Get the contents property: The contents property.
     * 
     * @return the contents value.
     */
    @Generated
    public ContentsFileDetails getContents() {
        return this.contents;
    }
}
