// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.brian.fun.service.implementation.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.generic.core.annotation.Generated;
import com.generic.core.annotation.Immutable;
import com.generic.core.models.BinaryData;

/**
 * The CreateUrlAttachmentRequest model.
 */
@Immutable
public final class CreateUrlAttachmentRequest {
    /*
     * The contents property.
     */
    @Generated
    @JsonProperty(value = "contents")
    private BinaryData contents;

    /**
     * Creates an instance of CreateUrlAttachmentRequest class.
     * 
     * @param contents the contents value to set.
     */
    @Generated
    @JsonCreator
    public CreateUrlAttachmentRequest(@JsonProperty(value = "contents") BinaryData contents) {
        this.contents = contents;
    }

    /**
     * Get the contents property: The contents property.
     * 
     * @return the contents value.
     */
    @Generated
    public BinaryData getContents() {
        return this.contents;
    }
}
