// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.brian.fun.service.implementation.models;

import com.brian.fun.service.models.TodoItem;
import com.generic.core.annotation.Fluent;
import com.generic.core.annotation.Generated;
import com.generic.core.models.BinaryData;
import java.util.List;

/**
 * The CreateFormRequest model.
 */
@Fluent
public final class CreateFormRequest {
    /*
     * The item property.
     */
    @Generated
    private TodoItem item;

    /*
     * The attachments property.
     */
    @Generated
    private List<BinaryData> attachments;

    /**
     * Creates an instance of CreateFormRequest class.
     * 
     * @param item the item value to set.
     */
    @Generated
    public CreateFormRequest(TodoItem item) {
        this.item = item;
    }

    /**
     * Get the item property: The item property.
     * 
     * @return the item value.
     */
    @Generated
    public TodoItem getItem() {
        return this.item;
    }

    /**
     * Get the attachments property: The attachments property.
     * 
     * @return the attachments value.
     */
    @Generated
    public List<BinaryData> getAttachments() {
        return this.attachments;
    }

    /**
     * Set the attachments property: The attachments property.
     * 
     * @param attachments the attachments value to set.
     * @return the CreateFormRequest object itself.
     */
    @Generated
    public CreateFormRequest setAttachments(List<BinaryData> attachments) {
        this.attachments = attachments;
        return this;
    }
}
