// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.brian.fun.service.implementation.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.generic.core.annotation.Generated;
import com.generic.core.annotation.Immutable;

/**
 * The ForgotPasswordRequest model.
 */
@Immutable
public final class ForgotPasswordRequest {
    /*
     * The email property.
     */
    @Generated
    @JsonProperty(value = "email")
    private String email;

    /**
     * Creates an instance of ForgotPasswordRequest class.
     * 
     * @param email the email value to set.
     */
    @Generated
    @JsonCreator
    public ForgotPasswordRequest(@JsonProperty(value = "email") String email) {
        this.email = email;
    }

    /**
     * Get the email property: The email property.
     * 
     * @return the email value.
     */
    @Generated
    public String getEmail() {
        return this.email;
    }
}
