// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.brian.fun.service.implementation.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.generic.core.annotation.Generated;
import com.generic.core.annotation.Immutable;

/**
 * The LoginRequest model.
 */
@Immutable
public final class LoginRequest {
    /*
     * The username property.
     */
    @Generated
    @JsonProperty(value = "username")
    private String username;

    /*
     * The password property.
     */
    @Generated
    @JsonProperty(value = "password")
    private String password;

    /**
     * Creates an instance of LoginRequest class.
     * 
     * @param username the username value to set.
     * @param password the password value to set.
     */
    @Generated
    @JsonCreator
    public LoginRequest(@JsonProperty(value = "username") String username,
        @JsonProperty(value = "password") String password) {
        this.username = username;
        this.password = password;
    }

    /**
     * Get the username property: The username property.
     * 
     * @return the username value.
     */
    @Generated
    public String getUsername() {
        return this.username;
    }

    /**
     * Get the password property: The password property.
     * 
     * @return the password value.
     */
    @Generated
    public String getPassword() {
        return this.password;
    }
}
