// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.brian.fun.service.implementation.models;

import com.brian.fun.service.models.TodoItemPatch;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.generic.core.annotation.Generated;
import com.generic.core.annotation.Immutable;

/**
 * The UpdateRequest model.
 */
@Immutable
public final class UpdateRequest {
    /*
     * The patch property.
     */
    @Generated
    @JsonProperty(value = "patch")
    private TodoItemPatch patch;

    /**
     * Creates an instance of UpdateRequest class.
     * 
     * @param patch the patch value to set.
     */
    @Generated
    @JsonCreator
    public UpdateRequest(@JsonProperty(value = "patch") TodoItemPatch patch) {
        this.patch = patch;
    }

    /**
     * Get the patch property: The patch property.
     * 
     * @return the patch value.
     */
    @Generated
    public TodoItemPatch getPatch() {
        return this.patch;
    }
}
